name: sci
channels:
  - pyviz 
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - gdal
  - basemap
  - biopython
  - bitarray
  - bokeh
  - cython
  - descartes
  - earthengine-api
  - fiona
  - folium
  - geemap
  - geographiclib
  - geojson
  - geopandas
  - geopy
  - geos
  - imageio
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyter_client
  - keras
  - mahotas
  - mapclassify
  - matplotlib
  - matplotlib-inline
  - msprime
  - netCDF4
  - numpy
  - oauth2client
  - pandas
  - psutil
  - pykrige
  - pyproj
  - pysal
  - python-dateutil
  - pyvcf
  - radian
  - rasterio
  - rasterstats
  - rio-cogeo
  - rio-color
  - rio-tiler
  - rioxarray
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sphinx
  - sphinx_rtd_theme
  - statsmodels
  - sympy
  - tensorflow
  - tskit
  - twine
  - urllib3
  - xarray
  - r-base
  - r-CCP
  - r-cowplot
  - r-dismo
  - r-ggplot2
  - r-ggthemes
  - r-irkernel
  - r-jsonlite
  - r-knitr
  - r-lme4
  - r-lmerTest
  - r-MASS
  - r-nlme
  - r-pals
  - r-phytools
  - r-plyr
  - r-randomForest
  - r-raster
  - r-rasterVis
  - r-rayshader
  - r-RColorBrewer
  - r-reshape2
  - r-rgdal
  - r-rmarkdown
  - r-sf
  - r-shiny
  - r-sp
  - r-SpatialML
  - r-tidyr
  - r-tidyverse
  - r-tmap
  - r-vcfR
  - r-vegan
  - r-wesanderson
  - pip:
    - geopandas
    - nlmpy
    - rasterio
    - rio-hist
    - teapot
