name: work
channels:
  - pyviz 
  - conda-forge
dependencies:
  - python=3.7
  - pip>=21.0
  - gdal>=3.1
  - earthengine-api>=0.1.2
  - imageio>=2.7
  - matplotlib>=3.2
  - basemap>=1.1
  - numpy>=1.17
  - scikit-image>=0.16
  - scikit-learn>=0.22
  - scipy>=1.4
  - sympy>=1.6
  - r-base>=4.0
  - r-CCP>=1.0
  - r-cowplot>=1.0
  - r-dismo>=1.3
  - r-ggplot2>=3.3
  - r-ggthemes>=4.0
  - r-irkernel>=1.0
  - r-jsonlite>=1.7
  - r-knitr>=1.1
  - r-lme4>=1.1
  - r-lmerTest>=3.0
  - r-MASS>=7.3
  - r-nlme>=3.1
  - r-pals>=1.7
  - r-phytools>=0.6
  - r-plyr>=1.7
  - r-randomForest>=4.4
  - r-raster>=3.2
  - r-rasterVis>=0.3
  - r-rayshader>=0.22
  - r-RColorBrewer>=1.1
  - r-reshape2>=1.2
  - r-rgdal>=1.5
  - r-rmarkdown>=2.6
  - r-sf>=0.9
  - r-shiny>=1.6
  - r-sp>=1.4
  - r-SpatialML>=0.1
  - r-tidyr>=1.0
  - r-tidyverse>=1.1
  - r-tmap>=3.3
  - r-vcfR>=1.10
  - r-vegan>=2.3
  - r-wesanderson>=0.2
  - pip:
    - biopython>=1.5
    - bitarray>=2.0
    - bokeh>=2.1
    - cartopy>=0.17
    - cython>=0.27
    - descartes>=0.9
    - fiona>=1.8
    - folium>=0.10
    - geemap>=0.8
    - geographiclib>=1.3
    - geojson>=2.3
    - geopandas>=0.7
    - geopy>=2.0
    - geos>=0.1
    - ipykernel>=5.3
    - ipython>=7.21
    - ipywidgets>=7.0
    - jupyter>=0.5
    - jupyter_client>=5.5
    - keras>=2.2
    - mahotas>=1.2
    - mapclassify
    - msprime>=0.7.4
    - netCDF4>=1.3
    - nlmpy>=0.1.5
    - oauth2client>=4.1
    - pandas>=1.0
    - pykrige>=1.5
    - pyproj>=2.
    - pysal>=2.4
    - pyvcf>=0.4
    - radian>=0.3
    - rio-cogeo>=2.1
    - rio-color>=0.4
    - rio-hist>=1.0
    - rio-tiler>=1.4
    - rasterio>=1.1
    - rasterstats>=0.13
    - shapely>=1.5
    - seaborn>=0.9
    - sphinx>=3.3
    - sphinx_rtd_theme>=0.3
    - statsmodels>=0.10
    - teapot>=2.3
    - tensorflow>=2.2
    - tksit>=0.2.3
    - twine>=3.2
    - urllib3>=1.24
    - xarray>=0.16
