name: sci
channels:
  - pyviz 
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - gdal
  - earthengine-api
  - imageio
  - matplotlib
  - basemap
  - numpy
  - scikit-image
  - scikit-learn
  - scipy
  - sympy
  - r-base
  - r-CCP
  - r-cowplot
  - r-dismo
  - r-ggplot2
  - r-ggthemes
  - r-irkernel
  - r-jsonlite
  - r-knitr
  - r-lme4
  - r-lmerTest
  - r-MASS
  - r-nlme
  - r-pals
  - r-phytools
  - r-plyr
  - r-randomForest
  - r-raster
  - r-rasterVis
  - r-rayshader
  - r-RColorBrewer
  - r-reshape2
  - r-rgdal
  - r-rmarkdown
  - r-sf
  - r-shiny
  - r-sp
  - r-SpatialML
  - r-tidyr
  - r-tidyverse
  - r-tmap
  - r-vcfR
  - r-vegan
  - r-wesanderson
  - pip:
    - biopython
    - bitarray
    - bokeh
    - cartopy
    - cython
    - descartes
    - fiona
    - folium
    - geemap
    - geographiclib
    - geojson
    - geopandas
    - geopy
    - geos
    - ipykernel
    - ipython
    - ipywidgets
    - jupyter
    - jupyter_client
    - keras
    - mahotas
    - mapclassify
    - msprime
    - netCDF4
    - nlmpy
    - oauth2client
    - pandas
    - psutil
    - pykrige
    - pyproj
    - pysal
    - pyvcf
    - radian
    - rio-cogeo
    - rio-color
    - rio-hist
    - rio-tiler
    - rasterio
    - rasterstats
    - shapely
    - seaborn
    - sphinx
    - sphinx_rtd_theme
    - statsmodels
    - teapot
    - tensorflow
    - tskit
    - twine
    - urllib3
    - xarray
